### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aalin** [solidjs/signals#12]
Hi!

I have been trying to implement a reactive system in Ruby, and I just found this repo a few days ago, and I just got everything to work. There are many obvious similarities with the code in this reporitory.

So I would like to know, what license is this code released under?

It would be awesome if someone could add a LICENSE file to the root of the repository.

Thanks!

**Comment by ryansolid** [comment]
Added thanks

**Comment by aalin** [comment]
Thanks a lot, @ryansolid!
