### ISSUE TITLE
Is this a Signals repo or a Solid Primitives repo?

### ISSUE THREAD

**Issue by titoBouzout** [solidjs/signals#9]
I'm actually not sure what's the scope of this repository.  If you could figure out and communicate, would be appreciated!

It is this ?
1. Signal's package
2. Solid Primitives package

If this is a Signals package, then maybe utilities like `map` and `selector` should be in a different package.

I expect  `map` and `selector` to be built with what https://github.com/solidjs/signals is exporting, in fact these two are perfect examples on how to use this package to get other primitives done.

**Comment by lxsmnsyc** [comment]
`selector` needs to be built-in because it requires some graph-specific logic to achieve perf improvements, and I believe that's the case.

**Comment by trusktr** [comment]
These primitives are useful, but we should strongly think about if they can be implemented *on top of* signals, effects, and memos (I think we all agree memos/deriveds are core, even in TC39 Signals). The more things we add here, the more unlikely it is we can use Solid as a counter-example to proposals like TC39 Signals, which in my opinon is already going in an undersireable direction by not providing a basic `effect` API and instead giving developers a foot gun and less ergonomic `Watcher` API.

I've written `selector` before, *on top of* my own signals and effects implementation, by using effects to do the wiring. Maybe it would be better on top of memos. We should explore the possibility of building on top and exhaust all possibilities before concluding that these primites should be in core.

To start off with, has anyone here already tried to build these primitives on top of plain signals/effects/memos? if so, do you have examples that did work or were not acceptable for some reason?

**Comment by titoBouzout** [comment]
I have built selector on top of the public API, it performs well and its pretty readable, not sure if I am missing something? 
The only thing that comes to mind maybe is memory consumption? (I mean comparing with solid version of the same primitive [leaving aside that solid seems to provide array selection])
https://github.com/potahtml/pota/blob/master/src/hooks/useSelector.js
